export const Constants = {
  DELETE_MESSAGE: 'Are you sure you want to remove this news?',
  DELETE_HEADER: 'Confirm Deletion',
  DepartmentList: [
    { id: 1, name: 'Administrators Wing' },
    { id: 2, name: 'Art & Culture Wing' },
    { id: 3, name: 'Business & Industry Wing' },
    { id: 4, name: 'Education Wing' },
    { id: 5, name: 'IT Wing' },
    { id: 6, name: 'Jurists Wing' },
    { id: 7, name: 'Media-Wing' },
    { id: 8, name: 'Medical Wing' },
    { id: 9, name: "Politicians' Service Wing" },
    { id: 10, name: 'Religious Wing' },
    { id: 11, name: 'Rural Development Wing' },
    { id: 12, name: 'Scientists and Engineers Wing' },
    { id: 13, name: 'Security Services Wing' },
    { id: 14, name: 'Social Service Wing' },
    { id: 15, name: 'Shipping, Aviation & Tourism Wing' },
    { id: 16, name: 'SpARC Wing' },
    { id: 17, name: 'Sports Wing' },
    { id: 18, name: 'Transport and Travel Wing' },
    { id: 19, name: 'Women Wing' },
    { id: 20, name: 'Youth Wing' },
  ],
};
